### ISSUE TITLE
upstream macro expansion fixes

### ISSUE THREAD

**Issue by gyorb** [Ericsson/clang#603]
- [x]  Fix functor-like macro expansion  #601
- [x] Fix macro expansion in CTU #599
- [x] Fix infinite recursion in macro expansion #591

**Comment by bruntib** [comment]
These have been done.
